### PR TITLE
Added GPL3 license

### PR DESCRIPTION
**Pull request by eriizu**

### CODE REVIEW

**Comment by d0p1s4m4** [comment]
Hello, the code is already licensed under BSD-3 see: 
https://github.com/Damdoshi/LibLapin/blob/3f9cf2cdb275394dd9e799bfbd3d2f17b663a212/debian/copyright#L1-L28

That's true that the debian folder may not be the first we look at (#13)

**Comment by eriizu** [comment]
Hi, thanks for pointing that out, didn't see it there.

In fact I intended to add the BSD-3 licence to the root of the repo, not the GPL-3. That's by bad.

Shall we consider moving the `/debian/copyright` file to `/license.txt` so that GitHub and other VCSs pick up on it? That would make things clearer for anyone accessing the repo.

**Comment by d0p1s4m4** [comment]
That's sound great idea to me because as far as I know the debian directory is currently useless/unused.

**Comment by eriizu** [comment]
I made the changes on another branch to discard this one. Moved to #18.

**Pull request closed without merging**
